
services:
  db:
    image: mysql:8.0
    container_name: fortune-db
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: fortune_service
      TZ: Asia/Seoul
    ports:
      - "3305:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  app:
    image: k1950035/fortune-backend:latest
    container_name: fortune-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fortune_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "1234"
      
      KAKAO_CLIENT_ID: "8491e41c71215f2ee7f33c66e8733bf1"
      KAKAO_REDIRECT_URI: "http://localhost:3000/auth/kakao/login"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: "gpt-4o-mini"
      OPENAI_API_URL: "https://api.openai.com/v1/chat/completions"

volumes:
  db_data: